spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
  security:
    basic:
      enabled: false
      #oauth2:
      #client:
      #registration:
      #auth0:
      #client-id: 6fjQDjkHIE9EAT51jKXFZvXIU7mQXnSo
      #client-secret: cN12bRCiwuYSP_L551G19BVR9n6ahuVuUSmysNQblwhUMIrVbe6plOptvhKVveLD
      #scope:
      #- openid
      #- profile
      #- email
      #provider:
      #auth0:
    #issuer-uri: https://dev-dlb1auyl1qwo3nd5.us.auth0.com/
  datasource:
    url: jdbc:postgresql://localhost:5432/EdeQuestion
    username: postgres
    password: 240696

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update

  logging:
    level:
      org.springframework.web: DEBUG

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

  media:
    location: mediaFiles
